config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :categories
  resources :transactions

  resources :groups
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :people
end

app/models/person.rb
class Person < ApplicationRecord
    belongs_to :group
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups=Group.all.order('groupname DESC')
    @NumberOfGroups=Group.count
  end

  def create
        group = Group.new(group_params)
      if group.save
      redirect_to action: "index"
    else
      render action: "index"
    end
  end

  def group_params
      params.require(:group).permit(:groupname, :code, :des1, :des2, :des3)
  end

  def destroy
    if Person.where(group_id: params[:id]).count > 0
      redirect_to action: "index", error: true
    else
     Group.find(params[:id]).destroy
     redirect_to action: "index"
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

def index
  @people=Person.all.order('name ASC')
  @groups = Group.all
  @NumberOfPeople = Person.count
  @AverageAge = Person.all.average(:age)
  @people=Person.all.order('name ASC')
 
end

def edit
  @person = Person.find(params[:id])
  @groups = Group.all
end

def new
  @people=Person.all
  @groups = Group.all
end

def create
  person = Person.new(person_params)
  if person.save
    redirect_to action: "index"
  else
    render action: "new"
  end
end

def destroy
  Person.find(params[:id]).destroy
  redirect_to action: "index"
end

def update
  person = Person.find(params[:id])
  if person.update_attributes(person_params)
    redirect_to action: "index"
  else
    render action: "edit"
  end
end
def person_params
  params.require(:person).permit(:name, :firstname, :group_id, :sex, :age, :email, :des1, :des2, :des3)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/groups/index.html.erb
<div class="container">
<h3>Bücher</h3>
<table class="table">
  <col class="col-sm-1">
  <tr>
    <%= form_for :group, url: {action: "create"}, class: "form-horizontal" do |g| %>
    <tr>
      <td><%=g.label :groupname, "TITEL"%></td>
      <td>
        <%= g.text_field :groupname, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%=g.label :code, "BESCHREIBUNG"%></td>
      <td>
        <%= g.text_field :code, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%=g.label :des1, "THEMA"%></td>
      <td>
        <%= g.text_field :des1, class: "form-control" %>
      </td>
    </tr>
    <tr>
    </tr>
    <tr>
      <td><%=g.label :des3, "ERSCHEINUNGSDATUM"%></td>
      <td>
        <%= g.text_field :des3, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%= g.submit "Save Book", class: "btn btn-success"%>  <% end %></td><td></td>
    </tr>
</table>
<table class="table">
  <col class="col-sm-1">
  <col class="col-sm-1">
  <col class="col-sm-2">
  <col class="col-sm-2">
  <col class="col-sm-2">
  <col class="col-sm-1">

<tr><td><h4>Buch</h4></td>
  <td><h4>Beschreibung</h4></td>
<td><h4>Thema</h4></td>
<td><h4>Erscheinungsdatum</h4></td>

</tr>
<% @groups.each do |g| %>
    <tr>
      <td><%= g.groupname %></td>
      <td><%= g.code %></td>
      <td><%= g.des1 %></td>
      <td><%= g.des2 %></td>
      <td><%= g.des3 %></td>
      <td><%= link_to "Delete", group_path(g), method: :delete, data: { confirm: "Delete Flight?" } , class: "btn btn-danger"%></td>
    </tr>
  <% end %>
<tr><td>Number of flights: <%=@NumberOfGroups%></td><td></td></tr>
<tr><td><%= link_to "Passengers", people_path, class: "btn btn-success"%></td><td></td></tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AEROPORT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"> </div>s
    <div class="col-md-6">
      <h3>Passengers#edit</h3>
    </div>
  </div>
  <%= form_for @person, url: {action: "update"}, class: "form-horizontal" do |p| %>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :name, "NAME:" %></div>
    <div class="col-md-7"><%= p.text_field :name, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :firstname, "FIRST:" %></div>s
    <div class="col-md-7"><%= p.text_field :firstname, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :group_id, "FLIGHT:" %></div>
    <div class="col-md-7"><%= p.collection_select :group_id, @groups, :id, :groupname, class: "form-control" %><br /><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :email, "EMAIL:" %></div>
    <div class="col-md-7"><%= p.text_field :email, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :age, "AGE:" %></div>
    <div class="col-md-7"><%= p.text_field :age, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :sex, "SEX:" %></div>
    <%if @person.sex%>
      <div class="col-md-2"><%= p.radio_button :sex, 0 %> MALE<br /><%= p.radio_button :sex, 1, :checked => true%> FEMALE<br /><br /></div>
    <%else%>
      <div class="col-md-2"><%= p.radio_button :sex, 0, :checked => true %> MALE<br /><%= p.radio_button :sex, 1%> FEMALE<br /><br /></div>
      <%end%>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des1, "PASSPORT:" %></div>
    <div class="col-md-7"><%= p.text_field :des1, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des2, "BIRTH:" %></div>
    <div class="col-md-7"><%= p.text_field :des2, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des3, "RATED:" %></div>
    <div class="col-md-7"><%= p.text_field :des3, class: "form-control" %><br /></div>
  </div>
  <br />
  <br />
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-10">
      <%= p.submit "SAVE PASSENGER", class: "btn btn-success"%>
      <%= link_to "CANCEL", people_path, class: "btn btn-danger" %>
    </div>
  </div>
  <% end %>
</div>

app/views/people/index.html.erb
<div class="container">
  <h3>PASSENGERS</h3>
  <table class="table">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <tr>
      <th>Nr</th>
      <th>FLIGHT</th>
      <th>NAME</th>
      <th>FIRST</th>
      <th>EMAIL</th>
      <th>AGE</th>
      <th>SEX</th>
      <th>PASSPORT</th>
      <th>BIRTH</th>
      <th>RATED</th>
      <th>EDIT</th>
      <th>DESTROY</th>
    </tr>
    <% @people.each do |p| %>
      <tr>
        <td><%= p.id %></td>
        <td><%=@groups.find(p.group_id).groupname%></td>
        <td><%= p.name %></td>
        <td><%= p.firstname %></td>
        <td><%= p.email %></td>
        <td><%= p.age %></td>
        <td><%if p.sex %>
            FEMALE
          <%else%>
            MALE
          <%end%></td>
        <td><%= p.des1 %></td>
        <td><%= p.des2 %></td>
        <td>
          <% if p.des3=="WANTED"%>
            <font color="red"><strong><%= p.des3 %><br /> Police is coming!</strong></font>
          <%else%>
          <%= p.des3 %>
        <%end%></td>
        <td><%= link_to "Edit", edit_person_path(p) , class: "btn btn-success"%></td>
        <td><%= link_to "Löschen", person_path(p), method: :delete, data: { confirm: "DESTROY PERSON?" } , class: "btn btn-danger"%></td>
      </tr>
    <% end %>
    <tr><td colspan="2">NUMBER OF PEOPLE: </td><td colspan="10"><%= @NumberOfPeople %></td></tr>
    <tr><td colspan="2">AVERAGE AGE: </td><td colspan="10"><%= @AverageAge %></td></tr>
    <tr><td colspan="2">FLIGHT: </td><td colspan="8">
      <%@groups.all.each do |g|%>

          <%i=0%>
        <%@people.all.each do |pp|%>
            <%if pp.group_id==g.id%>
                <%i=i+1%>
            <%end%>
          <%end%>
           <%=i%> PASSENGERS ON <%=g.groupname%><br>
      <%end%>


     </td></tr>
  </table>
  <h4>
    <%= link_to "ADD Passenger ", new_person_path, class: "btn btn-success"%>
    <%= link_to "FLIGHTS ", groups_path , class: "btn btn-success"%>
  </h4>
</div>

app/views/people/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-6">
      <h3>Passengers#new</h3>
    </div>
  </div>
  <%= form_for :person, url: {action: "create"}, class: "form-horizontal" do |p| %>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :name, "NAME:" %></div>
    <div class="col-md-7"><%= p.text_field :name, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :firstname, "FIRST:" %></div>
    <div class="col-md-7"><%= p.text_field :firstname, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :group_id, "FLIGHT:" %></div>
    <div class="col-md-7"><%= p.collection_select :group_id, @groups, :id, :groupname, class: "form-control" %><br /><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :email, "EMAIL:" %></div>
    <div class="col-md-7"><%= p.text_field :email, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :age, "AGE:" %></div>
    <div class="col-md-7"><%= p.text_field :age, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1">SEX:</div>
    <div class="col-md-2"><%= p.radio_button :sex, 0, :checked => true %> MALE<br />
      <%= p.radio_button :sex, 1%> FEMALE<br /><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des1, "PASSPORT:" %></div>
    <div class="col-md-7"><%= p.text_field :des1, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des2, "BIRTH:" %></div>
    <div class="col-md-7"><%= p.text_field :des2, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des3, "RATED:" %></div>
    <div class="col-md-7"><%= p.text_field :des3, class: "form-control" %><br /></div>
  </div>
  <br />
  <br />
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-10">
      <%= p.submit "SAVE PASSENGER", class: "btn btn-success"%>
      <%= link_to "CANCEL", people_path, class: "btn btn-danger" %>
    </div>
  </div>
  <% end %>
</div>